name: remote ssh command
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build docker image
        run: |
          docker build -t biscarch/corgo-bot .
          docker save -o $GITHUB_WORKSPACE/corgo-bot.tar biscarch/corgo-bot
      - name: scp docker image to DO
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DIGITAL_OCEAN_IP }}
          username: ${{ secrets.DIGITAL_OCEAN_USER }}
          key: ${{ secrets.DIGITAL_OCEAN_KEY }}
          port: 22
          source: ${{env.GITHUB_WORKSPACE}}/corgo-bot.tar
          target: /opt/corgo-bot.tar
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITAL_OCEAN_IP }}
          username: ${{ secrets.DIGITAL_OCEAN_USER }}
          key: ${{ secrets.DIGITAL_OCEAN_KEY }}
          port: 22
          script: |
            docker load -i /opt/corgo-bot.tar
            # rm /opt/corgo-bot.tar
