name: remote ssh command
on:
  push:
    branches:
      - corgi
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build docker image
        run: |
          docker build -t biscarch/corgo-bot .
          docker save -o corgo-bot.tar biscarch/corgo-bot
      - name: scp docker image to DO
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DIGITAL_OCEAN_IP }}
          username: ${{ secrets.DIGITAL_OCEAN_USER }}
          key: ${{ secrets.DIGITAL_OCEAN_KEY }}
          port: 22
          source: corgo-bot.tar
          target: /opt
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITAL_OCEAN_IP }}
          username: ${{ secrets.DIGITAL_OCEAN_USER }}
          key: ${{ secrets.DIGITAL_OCEAN_KEY }}
          port: 22
          script: |
            docker load -i /opt/corgo-bot.tar
            rm /opt/corgo-bot.tar
            docker kill $(docker ps -q)
            docker run --env-file /opt/corgo-bot.env -d biscarch/corgo-bot:latest
            docker system prune -f
      - name: Upload docker image artifact just in case
        uses: actions/upload-artifact@v1
        with:
          name: corgo-bot.tar
          path: corgo-bot.tar
